# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 06:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('buyer', '0001_initial'), ('buyer', '0002_auto_20170119_0958'), ('buyer', '0003_auto_20170119_1002'), ('buyer', '0004_auto_20170119_1245'), ('buyer', '0005_auto_20170119_1252'), ('buyer', '0006_dish'), ('buyer', '0007_auto_20170120_0717'), ('buyer', '0008_auto_20170120_0730'), ('buyer', '0009_auto_20170120_0736')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('g', 'Грамм'), ('l', 'Литр'), ('q', 'Штуки')], default='g', max_length=1, verbose_name='Ед. измерения')),
                ('carbs', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Углеводы')),
                ('fats', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Жиры')),
                ('proteins', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Белки')),
                ('calories', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Калории')),
                ('category', models.CharField(choices=[('1', 'Грибы'), ('2', 'Колбасные изделия'), ('3', 'Крупы и каши'), ('4', 'Масла и жиры'), ('5', 'Яйца'), ('6', 'Ягоды'), ('7', 'Фрукты'), ('8', 'Молочные продукты'), ('9', 'Мука и макаронные изделия'), ('10', 'Орехи и сухофрукты'), ('11', 'Мясопродукты'), ('12', 'Овощи и зелень'), ('13', 'Рыба и морепродукты'), ('14', 'Сыры и творог'), ('15', 'Хлебобулочные изделия'), ('16', 'Напитки алкогольные'), ('17', 'Напитки безалкогольные'), ('18', 'Соки и компоты')], default='1', max_length=2, verbose_name='Категория')),
                ('first_supplier', models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 1')),
                ('second_supplier', models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 2')),
                ('third_supplier', models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 3')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Рецепт и описание')),
                ('dish_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.Dish', verbose_name='Блюдо в качестве ингредиента')),
                ('ingredients', models.ManyToManyField(to='buyer.Ingredient', verbose_name='Ингредиенты')),
                ('category', models.CharField(choices=[('1', 'Холодные закуски'), ('2', 'Закуски'), ('3', 'Горячие закуски'), ('4', 'Вторые блюда'), ('5', 'Гарниры'), ('6', 'Десерты'), ('7', 'Барбекю'), ('8', 'Напитки')], default='2', max_length=2, verbose_name='Категория')),
                ('gross', models.PositiveIntegerField(default=50, verbose_name='Брутто')),
            ],
        ),
    ]
