# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 07:30
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('gross', models.PositiveIntegerField(default=50, verbose_name='Брутто')),
                ('description', models.TextField(verbose_name='Рецепт и описание')),
                ('category', models.CharField(choices=[('1', 'Холодные закуски'), ('2', 'Закуски'), ('3', 'Горячие закуски'), ('4', 'Вторые блюда'), ('5', 'Гарниры'), ('6', 'Десерты'), ('7', 'Барбекю'), ('8', 'Напитки')], default='2', max_length=2, verbose_name='Категория')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('first_supplier', models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 1')),
                ('second_supplier', models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 2')),
                ('third_supplier', models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 3')),
                ('unit', models.CharField(choices=[('g', 'Грамм'), ('l', 'Литр'), ('q', 'Штуки')], default='g', max_length=1, verbose_name='Ед. измерения')),
                ('category', models.CharField(choices=[('1', 'Грибы'), ('2', 'Колбасные изделия'), ('3', 'Крупы и каши'), ('4', 'Масла и жиры'), ('5', 'Яйца'), ('6', 'Ягоды'), ('7', 'Фрукты'), ('8', 'Молочные продукты'), ('9', 'Мука и макаронные изделия'), ('10', 'Орехи и сухофрукты'), ('11', 'Мясопродукты'), ('12', 'Овощи и зелень'), ('13', 'Рыба и морепродукты'), ('14', 'Сыры и творог'), ('15', 'Хлебобулочные изделия'), ('16', 'Напитки алкогольные'), ('17', 'Напитки безалкогольные'), ('18', 'Соки и компоты')], default='1', max_length=2, verbose_name='Категория')),
                ('proteins', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Жиры')),
                ('carbs', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Углеводы')),
                ('calories', models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Калории')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='buyer.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
