# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='souce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.Dish', verbose_name='Соус'),
        ),
    ]
