# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='supplier',
            field=models.CharField(max_length=200, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Грамм'), ('l', 'Литр'), ('q', 'Штуки')], default='g', max_length=1, verbose_name='Ед. измерения'),
        ),
    ]
