# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20170123_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='data',
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='buyer.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
