# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 08:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20170119_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteins',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Белки'),
        ),
    ]
