# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_dish_souce'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='souce_q',
            field=models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Количество соуса'),
        ),
    ]
