# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20170123_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TestIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatever', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.TestDish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.TestIngredient')),
            ],
        ),
        migrations.AddField(
            model_name='testdish',
            name='ingredeints',
            field=models.ManyToManyField(through='buyer.TestRecipe', to='buyer.TestIngredient', verbose_name='Ингредиенты'),
        ),
    ]
