# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 10:45
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20170119_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('1', 'Грибы'), ('2', 'Колбасные изделия'), ('3', 'Крупы и каши'), ('4', 'Масла и жиры'), ('5', 'Яйца'), ('6', 'Ягоды'), ('7', 'Фрукты'), ('8', 'Молочные продукты'), ('9', 'Мука и макаронные изделия'), ('10', 'Орехи и сухофрукты'), ('11', 'Мясопродукты'), ('12', 'Овощи и зелень'), ('13', 'Рыба и морепродукты'), ('14', 'Сыры и творог'), ('15', 'Хлебобулочные изделия'), ('16', 'Напитки алкогольные'), ('17', 'Напитки безалкогольные'), ('18', 'Соки и компоты')], default='1', max_length=1, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='first_supplier',
            field=models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 1'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='second_supplier',
            field=models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 2'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='third_supplier',
            field=models.CharField(default='Novus', max_length=200, verbose_name='Поставщик 3'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.DecimalField(decimal_places=3, default=Decimal('5.00'), max_digits=10, verbose_name='Белки'),
        ),
    ]
