# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_dish_souce_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.PositiveIntegerField(default='10', verbose_name='Брутто'),
        ),
    ]
