# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_auto_20170119_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Рецепт и описание')),
                ('dish_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Dish', verbose_name='Блюдо в качестве ингредиента')),
                ('ingredients', models.ManyToManyField(to='buyer.Ingredient', verbose_name='Ингредиенты')),
            ],
        ),
    ]
