# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_auto_20170129_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='buyer.Recipe', to='buyer.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
