# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='buyer.Recipe', to='buyer.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
