# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_auto_20170120_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('1', 'Холодные закуски'), ('2', 'Закуски'), ('3', 'Горячие закуски'), ('4', 'Вторые блюда'), ('5', 'Гарниры'), ('6', 'Десерты'), ('7', 'Барбекю'), ('8', 'Напитки')], default='2', max_length=2, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='dish',
            name='gross',
            field=models.PositiveIntegerField(default=50, verbose_name='Брутто'),
        ),
    ]
