# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:44
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20170129_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='souce_q',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, verbose_name='Количество соуса'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, verbose_name='Белки'),
        ),
    ]
