# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20170120_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.Dish', verbose_name='Блюдо в качестве ингредиента'),
        ),
    ]
