# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_auto_20170129_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerListIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='souce',
            new_name='sauce',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='souce_q',
        ),
        migrations.AddField(
            model_name='dish',
            name='sauce_q',
            field=models.PositiveIntegerField(default='0', verbose_name='Количество соуса'),
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(default='1', verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('1', 'Холодные закуски'), ('2', 'Закуски'), ('3', 'Горячие закуски'), ('4', 'Вторые блюда'), ('5', 'Гарниры'), ('6', 'Десерты'), ('7', 'Барбекю'), ('8', 'Напитки'), ('9', 'Соусы'), ('10', 'Спорт'), ('11', 'Канапе'), ('12', 'Салаты'), ('13', 'Намазки')], default='2', max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('1', 'Грибы'), ('2', 'Колбасные изделия'), ('3', 'Крупы и каши'), ('4', 'Масла и жиры'), ('5', 'Яйца'), ('6', 'Ягоды'), ('7', 'Фрукты'), ('8', 'Молочные продукты'), ('9', 'Мука и макаронные изделия'), ('10', 'Орехи и сухофрукты'), ('11', 'Мясопродукты'), ('12', 'Овощи и зелень'), ('13', 'Рыба и морепродукты'), ('14', 'Сыры и творог'), ('15', 'Хлебобулочные изделия'), ('16', 'Напитки алкогольные'), ('17', 'Напитки безалкогольные'), ('18', 'Соки и компоты'), ('19', 'Приправы и специи'), ('20', 'Разное')], default='1', max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='first_supplier',
            field=models.CharField(default='Novus', max_length=200, verbose_name='Производитель 1'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='second_supplier',
            field=models.CharField(default='Novus', max_length=200, verbose_name='Производитель 2'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='third_supplier',
            field=models.CharField(default='Novus', max_length=200, verbose_name='Производитель 3'),
        ),
        migrations.AddField(
            model_name='buyerlistintermediate',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Dish'),
        ),
        migrations.AddField(
            model_name='buyerlist',
            name='dishes',
            field=models.ManyToManyField(to='buyer.BuyerListIntermediate', verbose_name='Блюда'),
        ),
    ]
