# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 06:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_dish_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Ingredient'): 1}),
        ),
    ]
