# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_remove_dish_privet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='gross',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Брутто'),
        ),
    ]
