# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_auto_20170203_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='sss',
            field=models.ManyToManyField(to='buyer.Dish', verbose_name='Соус'),
        ),
    ]
