# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_auto_20170123_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='data',
        ),
    ]
