# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_auto_20170203_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='sss',
        ),
        migrations.AddField(
            model_name='dish',
            name='ssouce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.Dish', verbose_name='Соус'),
        ),
    ]
