# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0016_auto_20170203_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='sauce_q',
            field=models.PositiveIntegerField(default='0', verbose_name='Количество соуса'),
        ),
    ]
