# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0020_auto_20170213_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.PositiveIntegerField(default='1', verbose_name='Вес'),
        ),
    ]
