# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0021_dish_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerListIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='buyerlist',
            name='dishes',
            field=models.ManyToManyField(to='buyer.BuyerListIntermediate', verbose_name='Блюда'),
        ),
    ]
